"""add facebook pages

Revision ID: 13526740ae59
Revises: 914c0380fd63
Create Date: 2026-08-13 01:06:19.764604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13526740ae59'
down_revision: Union[str, Sequence[str], None] = '914c0380fd63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facebook_pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meta_connection_id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.String(), nullable=False),
    sa.Column('page_name', sa.String(), nullable=False),
    sa.Column('page_access_token', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['meta_connection_id'], ['meta_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facebook_pages_id'), 'facebook_pages', ['id'], unique=False)
    op.create_index(op.f('ix_facebook_pages_meta_connection_id'), 'facebook_pages', ['meta_connection_id'], unique=False)
    op.create_index(op.f('ix_facebook_pages_page_id'), 'facebook_pages', ['page_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facebook_pages_page_id'), table_name='facebook_pages')
    op.drop_index(op.f('ix_facebook_pages_meta_connection_id'), table_name='facebook_pages')
    op.drop_index(op.f('ix_facebook_pages_id'), table_name='facebook_pages')
    op.drop_table('facebook_pages')
    # ### end Alembic commands ###
