"""add scheduled_at to posts

Revision ID: 4f5db79b6577
Revises: 14701bec60ef
Create Date: 2026-08-18 13:37:22.684825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f5db79b6577'
down_revision: Union[str, Sequence[str], None] = '14701bec60ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_posts_scheduled_at'), 'posts', ['scheduled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_scheduled_at'), table_name='posts')
    op.drop_column('posts', 'scheduled_at')
    # ### end Alembic commands ###
