"""add platforms to posts

Revision ID: 62f43b53c412
Revises: 4f5db79b6577
Create Date: 2026-08-18 14:12:38.227989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62f43b53c412'
down_revision: Union[str, Sequence[str], None] = '4f5db79b6577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add column temporarily as nullable so existing posts can be migrated.
    op.add_column(
        "posts",
        sa.Column(
            "platforms",
            sa.JSON(),
            nullable=True,
        ),
    )

    # Existing posts were published to Facebook/Instagram before
    # the platforms column existed. Infer their platforms from IDs.
    op.execute(
        """
        UPDATE posts
        SET platforms = CASE
            WHEN facebook_post_id IS NOT NULL
                 AND instagram_media_id IS NOT NULL
                THEN '["facebook", "instagram"]'::json
            WHEN facebook_post_id IS NOT NULL
                THEN '["facebook"]'::json
            WHEN instagram_media_id IS NOT NULL
                THEN '["instagram"]'::json
            ELSE '[]'::json
        END
        """
    )

    # Now that every existing row has a value, make it NOT NULL.
    op.alter_column(
        "posts",
        "platforms",
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'platforms')
    # ### end Alembic commands ###
