"""add meta connections

Revision ID: 914c0380fd63
Revises: c4a5b6d7e8f9
Create Date: 2026-08-12 12:31:00.128794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '914c0380fd63'
down_revision: Union[str, Sequence[str], None] = 'c4a5b6d7e8f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('meta_user_id', sa.String(), nullable=False),
    sa.Column('meta_name', sa.String(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('token_type', sa.String(), nullable=True),
    sa.Column('expires_in', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meta_connections_id'), 'meta_connections', ['id'], unique=False)
    op.create_index(op.f('ix_meta_connections_meta_user_id'), 'meta_connections', ['meta_user_id'], unique=False)
    op.create_index(op.f('ix_meta_connections_user_id'), 'meta_connections', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meta_connections_user_id'), table_name='meta_connections')
    op.drop_index(op.f('ix_meta_connections_meta_user_id'), table_name='meta_connections')
    op.drop_index(op.f('ix_meta_connections_id'), table_name='meta_connections')
    op.drop_table('meta_connections')
    # ### end Alembic commands ###
