"""create auth tables

Revision ID: ee56037cf77c
Revises: 
Create Date: 2026-08-04 09:40:13.023999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee56037cf77c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE role AS ENUM ('ADMIN', 'MANAGER', 'EDITOR', 'VIEWER')")
    op.add_column('organization_members', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('organization_members', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.execute("ALTER TABLE organization_members ALTER COLUMN role TYPE role USING role::role")
    op.drop_index(op.f('idx_members_org'), table_name='organization_members')
    op.drop_index(op.f('idx_members_user'), table_name='organization_members')
    op.drop_constraint(op.f('unique_membership'), 'organization_members', type_='unique')
    op.add_column('organizations', sa.Column('slug', sa.String(length=100), nullable=False))
    op.add_column('organizations', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('organizations', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_unique_constraint(None, 'organizations', ['slug'])
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_constraint(None, 'organizations', type_='unique')
    op.alter_column('organizations', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('organizations', 'updated_at')
    op.drop_column('organizations', 'slug')
    op.create_unique_constraint(op.f('unique_membership'), 'organization_members', ['user_id', 'organization_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_members_user'), 'organization_members', ['user_id'], unique=False)
    op.create_index(op.f('idx_members_org'), 'organization_members', ['organization_id'], unique=False)
    op.alter_column('organization_members', 'role',
               existing_type=sa.Enum('ADMIN', 'MANAGER', 'EDITOR', 'VIEWER', name='role'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('organization_members', 'updated_at')
    op.drop_column('organization_members', 'created_at')
    op.execute('DROP TYPE role')
    # ### end Alembic commands ###
